### ISSUE TITLE
Image Format

### ISSUE THREAD

**Issue by aswinpreman06** [1998code/DALLE-2-App#15]
Hi,
The image format in response is coming in WEBP format.Is there any way to get response in jpeg or png?

Thanks,
Aswin Preman

**Comment by 1998code** [comment]
Hi @aswinpreman06, you may open an issue at https://github.com/ezzcodeezzlife/dalle-node/issues

**Comment by 1998code** [comment]
Hi @aswinpreman06, the app now supports different formats. 😉
