### ISSUE TITLE
Bearer Token Issue

### ISSUE THREAD

**Issue by xishoon** [1998code/DALLE-2-App#16]
URL to get Bearer Token `https://labs.openai.com/api/labs/tasks` requires username and password. I tried with my username and password but its not working. How can I get the Bearer Token ?

**Comment by ezzcodeezzlife** [comment]
follow the steps in this readme: https://github.com/ezzcodeezzlife/dalle2-in-python 🚀

**Comment by xishoon** [comment]
@ezzcodeezzlife I can get the bearer token from the Header but this token expires after some time.
