### ISSUE TITLE
Is this deprecated? Or the current best practice?

### ISSUE THREAD

**Issue by bjshumway** [1998code/DALLE-2-App#17]
Hey, I see open AI has an API library... but that uses Python.... I prefer to use Node as I'm much more familiar with it.

Is this technique considered a "hack" or is effectively doing the same thing the python technique would do?

Thanks

**Comment by bjshumway** [comment]
Oh... just saw... the website allows you to toggle between node / curl / python... so I think this technique is deprecated... for now until you change it.

**Comment by 1998code** [comment]
Hi @bjshumway,

V2.0.0 is available now. Have fun :)

![Xnapper-2023-01-15-23 41 21](https://user-images.githubusercontent.com/54872601/212551632-45b55c60-f0e7-4d69-a200-f6fd28d68566.jpg)
