### ISSUE TITLE
’Something went wrong. Try again.‘

### ISSUE THREAD

**Issue by VincentHan888** [1998code/DALLE-2-App#18]
I opened the Vercel page and entered some information, but it displayed 'Something went wrong. Try again.' Even after I cloned and deployed it locally, I still got the same error code. Is there something wrong?
![WX20230322-182258@2x](https://user-images.githubusercontent.com/118708340/226875113-376228f8-3f13-49be-a375-ee5987f34013.png)

**Comment by 1998code** [comment]
Hi @VincentHan888 be sure to include ```sk-``` in your token.

![CleanShot 2023-03-26 at 11 12 20@2x](https://user-images.githubusercontent.com/54872601/227753196-3a7df095-fb86-4bab-832b-0a9e268a39e5.png)
