### ISSUE TITLE
Generate 4 pictures instead of 6

### ISSUE THREAD

**Issue by 7flash** [1998code/DALLE-2-App#7]
Accordingly to recent changes in beta..

**Comment by 7flash** [comment]
https://github.com/1998code/DALLE-2-App/pull/6

**Comment by ezzcodeezzlife** [comment]
yes this was fixed in #6

**Comment by 7flash** [comment]
https://github.com/1998code/DALLE-2-App/pull/10

**Comment by 1998code** [comment]
Merged with thanks :)
