### ISSUE TITLE
FUNCTION_INVOCATION_TIMEOUT

### ISSUE THREAD

**Issue by 7flash** [1998code/DALLE-2-App#9]

**Comment by ezzcodeezzlife** [comment]
can you provide a little bit more information about this? happy to fix all issues 🚒

**Comment by 7flash** [comment]
This error happened to me when trying to deploy on vercel.. Free hobby plan has limitation.. solved by moving to self-hosted server..

**Comment by ezzcodeezzlife** [comment]
can you share the link to your deployment?
